const Recipes = require('../models/Recipes')



const recipes = 
[
    {
      recipes_name:"Philly Cheesesteak Sloppy Joes",
      description:"Take the best of two classic sandwiches—sloppy joes and Philly cheesesteaks—to make these cheesy, meaty, and saucy cheesesteak sloppy joes!",
      ingredients:"2 tablespoons unsalted butter, 1 small white onion, chopped, 1 green bell pepper, seeded and chopped, 1 pound lean beef, 90/10 blend, 1/2 cup beef stock, 1/4 cup ketchup, 2 tablespoons Worcestershire sauce, 1/2 teaspoon garlic powder, 1/2 teaspoon kosher salt, 1/2 teaspoon black pepper, 12 slices provolone cheese, divided, 6 brioche buns, store-bought or homemade",
      servings:"6 servings",
      preptime:"10 mins",
      cooktime:"30 mins",
      totaltime:"40 mins",
      instructions:"Step 1:Cook the vegetables:In a large skillet set over medium heat, melt the butter. Add the onions and bell peppers. Cook until soften, 6 to 7 minutes, stirring frequently. The vegetables shouldn’t brown at this point, just soften. Step 2:Cook the beef:Add the ground beef and use a wooden spoon to break it up into small pieces as it cooks. Cook until the meat is browned, 5 to 6 minutes. Step 3:Make it saucy:Stir in the stock, ketchup, Worcestershire sauce, garlic powder, salt, and black pepper. Turn the heat down to low and simmer for 4 to 5 minutes until the mixture thickens. Stack 6 slices provolone cheese on a cutting board and use a chef’s knife to cut them into 1/2-inch pieces. Right before serving, stir in the cut cheese. Step 4:Assemble the sloppy joes: Toast the brioche buns in a toaster oven or toaster. Lay the remaining 6 slices provolone cheese on each brioche bun half. Top the cheese with heaping spoonfuls of the sloppy joe mixture and the top bun. Serve warm. If you have leftover sloppy joe mixture, good news! It keeps beautifully in the fridge for 4 to 5 days and reheats well in the microwave or in a skillet with a splash of water or stock. You can freeze the mixture in freezer-safe container for 3 months. Thaw it before reheating. If you need to thaw it quickly, you can do so in the microwave.",
      images:"https://www.simplyrecipes.com/thmb/mUd-uPsPpXw68kxJEx00gU0PFLM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Philly-Cheesesteak-Sloppy-Joes-LEAD-04-27e9055fa2744039989619dcafef0551.jpg",
      allergens:"Eggs",
      difficulty:"Medium",
    },
    {
      recipes_name:"Kale and Mushroom Egg Bites",
      description:"These veggie-packed and easily-reheatable kale and mushroom egg bites are the easiest way to start your day with a simple, nutritious breakfast—even if you are racing out the door without a second to spare.",
      ingredients:"2 tablespoons unsalted butter, divided, 5 large leaves fresh kale, stems removed and roughly chopped, 3 portobello mushroom caps, cleaned and roughly chopped1 teaspoon kosher salt, divided, 9 large eggs, 1/4 cup half and half, Aleppo pepper or smoked paprika, to taste (optional)",
      servings:"6 Servings",  
      preptime:"15 mins",
      cooktime:"28 mins",
      totaltime:"43 mins",
      instructions: "Step 1: Preheat the oven to 325ºF. Step 2: Prepare the muffin tin: Microwave 1 tablespoon of the butter in a microwave-safe bowl or measuring cup until melted, 15 to 20 seconds. Using a brush or paper towel, thoroughly coat each well in a 12-well muffin or cupcake tin generously with the melted butter. Step 3:Process the filling: Chopped kale until chopped into small pieces. Transfer to a bowl and repeat with portobello mushrooms. Step 4: Cook the filling: Place a large skillet over medium heat and add 1 tablespoon butter. When the butter is foamy, add the chopped mushrooms and 1/4 teaspoon of salt. Sauté for 4 to 5 minutes, stirring frequently, or until all liquid from the mushrooms has been released (the mushrooms will reduce in volume significantly).Add the kale and another 1/4 teaspoon salt to the skillet and sauté until wilted and tender, 4 to 5 minutes more. Remove the skillet from the heat and allow the vegetables to cool slightly. Step 5: Prepare the egg mixture: Using a blender, blend the eggs, half and half, and 1/2 teaspoon salt until the mixture is frothy and completely homogenous, 10 to 15 seconds. Alternatively, whisk together thoroughly in a bowl. Step 6: Fill the wells: Divide the cooled kale and portobello mushroom mixture among the 12 buttered wells of the muffin tin, then carefully fill each well no more than 3/4 full with the egg mixture. Use a small spoon or butter knife to combine the ingredients in each well, then finish with a sprinkle of smoked paprika or Aleppo pepper on top of each well, if desired. Step 7: Bake the egg bites: Bake the egg bites, rotating the muffin tin halfway through to ensure even baking, 16 to 19 minutes. When finished, the egg bites will be puffed and barely set in the middle, but not at all hard. Test for doneness occasionally by poking the center of each egg bite—perfectly cooked egg bites will be bouncy and just set, as they will continue to set up as they cool. Step 8: Serve or store the egg bites: Remove the cooked egg bites from the oven and run a butter knife around the edge of each well to release any stuck-on bits. Let cool slightly, then remove to a plate. Serve warm, or allow to cool to room temperature and store in an airtight container in the refrigerator for up to 5 days.",
      images:"https://www.simplyrecipes.com/thmb/sa7aFD1tUouH_3cQqZNdmjXlgaM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Kale-Portobello-Egg-Bites-LEAD-10-f6fcb5383d2a4c64a2e2e163c1fe7d3d.jpg",
      allergens:"Eggs, Milk",
      difficulty:"Easy",
    },
    {
      recipes_name:"Sheet Pan Buttermilk Pancakes",
      description:"This sheet pan pancake recipe is the solution to breakfasts that are special yet stress-free. Bake a giant buttermilk pancake on a sheet pan and cut it into squares for serving. Freezes great for quick school day brekkies!",
      ingredients:"8 tablespoons (1 stick) unsalted butter, melted and cooled, divided, 2 1/2 cup (313g) all-purpose flour, 1 tablespoon baking powder, 1 teaspoon baking soda, 1/2 teaspoon salt, 1/2 cup brown sugar, 2 cups buttermilk, 2 large eggs, 1 teaspoon vanilla extract, 1 teaspoon finely grated lemon zest, 1 cup blueberries, divided, 1 cup raspberries, divided",
      servings:"12 serving",
      preptime:"10 mins",
      cooktime:" 20 mins",
      totaltime:"30 mins",
      instructions:"Step 1:Preheat oven to 425°F:Place a rack in the upper third of the oven. Preheat the oven to 425°F. Step 2:Grease the baking sheet: Pour 2 tablespoons of the melted butter on a 15x10.5-inch sheet pan. Using a pastry brush, brush the butter on the bottom of the baking sheet and up the sides. Step 3:Sift the dry ingredients: Sift the flour, baking powder, baking soda, and salt into a medium bowl. Step 4: Combine the wet ingredients: In a large bowl, combine the buttermilk, eggs, vanilla, lemon zest, and sugar. Whisk vigorously until combined. Step 5: Fold the dry ingredients into the wet: Pour 1/3 of the dry ingredients into the wet ingredients. Fold together using a silicone spatula. Repeat until all the dry ingredients are combined with the wet. Continue to fold until there are no streaks of flour. Mix until there is no dry flour on the bottom of the bowl. Fold in 4 tablespoons of the melted butter. Lumps are fine. Your batter should look like loose ricotta. Step 6: Fold in half of the fruit: Fold in half of the blueberries and raspberries into the pancake batter. Step 7: Pour the batter into the pan: Pour the batter into the buttered pan. Using a silicone spatula, spread the batter around so it covers the bottom of the baking sheet completely and is even on top. Step 8: Sprinkle the remaining fruit on top: Sprinkle the remaining blueberries and raspberries on top of the batter. Step 9: Bake the pancake: Bake the pancake for 15 minutes. Insert toothpick in the middle of the pancake. If it is free from wet batter, it's done. If not, bake for 5 minutes longer. The top of your pancake should be lightly toasted. Step 10: Brush the remaining butter on the pancake: Right after it comes out of the oven, brush the remaining 2 tablespoons of butter on the pancake. Step 11: Cut and serve: Allow the pancake to cool slightly, approximately 3 minutes. Cut into squares and serve with warm maple syrup. Step 12: Storage: Once cooked, you can leave sheet pan pancakes at room temperature for up to 2 hours. Put leftover slices in a zip-top bag or another airtight container and refrigerate for 2-3 days.",
      images:"https://www.simplyrecipes.com/thmb/yICvDeFKzOwH852vzqKk6qwH1KY=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes_Sheetpan-Pancakes_LEAD_3-11fede29492841bca349511544941a0c.jpg",
      allergens:"Eggs, Milk",
      difficulty:"Easy",
    },
    {
      recipes_name:"Peanut Butter and Chocolate Chip Pancakes",
      description:"These fluffy peanut butter pancakes with chocolate chips are my daughter’s favorite and soon-to-be yours too!",
      ingredients:"2 cups (260g)  all-purpose flour, 2 teaspoons baking powder, 1/4 teaspoon salt, 2 large eggs, 2 cups whole milk, 3/4 cup smooth peanut butter, 2 tablespoons melted butter, plus more for cooking pancakes, 4 teaspoons honey, 1 cup milk chocolate chips",
      servings:"6 servings",
      preptime:"5 mins",
      cooktime:"10 mins",
      totaltime:"15 mins",
      instructions:"Step 1: Combine the dry ingredients: In a medium bowl, add the flour, baking powder, and salt. Whisk to combine. Set it aside.. Step 2:Combine wet ingredients: In a large bowl, beat the eggs until the whites and yolks are combine. Then, add milk, peanut butter, melted butter, and honey. Stir well to incorporate. Step 3:Combine batter and add chocolate chips: Add the dry ingredients into the wet ingredients and mix until just incorporated. Stir in the chocolate chips. Step 4: Cook the pancakes: In a large skillet or griddle set to medium heat, add about 1/2 tablespoon butter. Pour a heaping tablespoon of batter in at a time, making silver dollar-sized pancakes. Leave plenty of space in between each pancake. Cook for 2 to 3 minutes, then flip. They are ready to flip when small bubbles appear on top and the edges start to brown. Cook the other side for 2 to 3 minutes. Add more butter to the skillet as needed. Step 5: Serve: Serve the pancakes immediately—syrup is optional for these sweet pancakes! Cool leftovers and refrigerate in an airtight container for a day or two. You can reheat them briefly in a toaster oven or let them warm to room temperature and eat them that way.",
      images:"https://www.simplyrecipes.com/thmb/2LaDXUvRsHsXGBsOdAPmGIzYyOQ=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes_Buckeye-Pancakes_LEAD_2-22356e0d04204ac0910508be2d2bd4c2.jpg",
      allergens:"Eggs, Milk, Nuts",
      difficulty:"Easy",
    },
    {
      recipes_name:"The Ultimate Quesadilla",
      description:"Here's how to make classic Mexican and Tex-Mex cheese quesadillas! Just toasted tortillas with melted cheese, griddled with our special technique. Make it yours with your favorite add-ins and toppings.",
      ingredients:"Large flour tortillas, Grated cheese such as mild or sharp cheddar, or Monterey Jack, Olive oil or butter, Sliced mushrooms, Green onions, Black olives, sliced, Fresh tomatoes, diced, Chicken pieces, Avocado, Lettuce, Apple cider vinegar, Kosher salt",
      servings:"1 serving",
      preptime:"5 mins",
      cooktime:"7 mins",
      totaltime:"12 mins",
      instructions:"Step 1:Heat the tortillas until air pockets form: Heat a large skillet (cast iron works great) on medium high heat. Add a small amount of oil (about 1/2 teaspoon) and spread it around the bottom of the pan with a spatula (you could use butter as well). Take one large flour tortilla and place it in the pan. Flip the tortilla over a few times, 10 seconds between flips. Air pockets should begin to form within the tortilla. Step 2: Add the cheese and other ingredients: When pockets of air begin to form, take a handful of grated cheese, sprinkle over the top of the tortilla, making sure that the cheese does not land on the pan itself. Add whatever additional ingredients you choose - green onion, sliced mushrooms, olives, tomatoes, etc. If you would like your quesadilla to be a chicken quesadilla, add some diced cooked chicken. Take care not to layer on the ingredients too thickly - this is a quesadilla, not a quiche! Step 3: Lower the heat and cover pan: Reduce the heat to low and cover the pan. The pan should be hot enough by now to have plenty of residual heat to melt the cheese and brown the tortilla. If the quesadilla begins to smoke too much, remove from the heat. After a minute, check to see if the cheese is melted. If not, return the cover and keep checking every minute until the cheese is melted. Step 4:Fold the tortilla over: When the cheese is sufficiently melted, use a spatula to lift up one side of the quesadilla and flip over the other side, as if you were making an omelette. The tortilla should by now be browned slightly. If it is not browned, turn the heat up to high and flip the quesadilla over every 10 seconds or so until it gets browned. Step 5: Remove quesadilla from pan and cut into wedges: To make the lettuce to accompany the quesadilla, thinly slice some iceberg lettuce. Sprinkle some cider vinegar on it and some salt. Serve with the lettuce, salsa, sour cream, and guacamole.",
      images:"https://www.simplyrecipes.com/thmb/95WEP5_i0u_SAzDTEJjxlyZLcxU=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Quesadilla-LEAD-4-523a569564b4453484be4cdf05ce0d6a.jpg",
      allergens:"Milk",
      difficulty:"Easy",
    },
    {
      recipes_name:"Microwave Baked Potato",
      description:"It is hard to improve on the baked potato except for one factor: time. This microwave baked potato recipe takes a fraction of the time and is just as delicious.",
      ingredients:"1 large (10 to 12-ounce) russet potato, 1 teaspoon olive oil, tablespoon butter, 1/4 cup shredded cheddar cheese, 1 tablespoon sour cream, 1 teaspoon minced chives, Salt and pepper, to taste",
      servings: "1 serving",
      preptime:"3 mins",
      cooktime:"10 mins",
      totaltime:"13 mins",
      instructions:" Step 1:Prepare the potato:If you would like a crispy skin on your baked potato, preheat the oven to 450°F, Scrub the potato well. Dry it off and poke it a few times on all sides with a fork. Step 2: Microwave the potato:Place the potato on a microwave-safe plate and microwave it for 8 to 12 minutes, flipping it once halfway through. For a medium-large potato cooked in a 1,000-watt microwave, the cook time will be about 10 minutes. Your potato will be steaming hot when it is done. Press on it a bit with your thumb and it should give easily to pressure. You should be able to pierce it through the center with a fork or paring knife with little resistance. If it feels firm at all, place it back in the microwave for 1-2 minutes longer. Step 3: Crisp the skin (optional): If you would like a crispy, salty skin on your potato (my favorite), coat the microwaved potato on all sides with olive oil and sprinkle with salt. Bake until the skin is cracking and crispy, about 10 minutes. Step 4:Serve the potato: Slice down the length of the hot potato halfway through to expose the interior. Top with your choice of toppings while hot, such as butter, cheese, sour cream, and/or chives. Season with salt and pepper to taste. Store leftovers in an airtight container in the fridge for up to 3 days. You can reheat in the microwave, but I prefer to reheat the potatoes in a 400°F oven for 10 minutes so they get crispy on the outside.",
      images:"https://www.simplyrecipes.com/thmb/j0AIoCMJ6EF5QRPDt7uzrPRZioA=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Microwaved-Baked-Potato-LEAD-01-734e3c50471442598f791c8afe95617f.jpg",
      allergens:"Milk",
      difficulty:"Easy",
    },
    {
      recipes_name:"Grilled Cheese BLT",
      description:"Finally! This Grilled Cheese BLT means you'll never have to choose between two delicious sandwiches for your lunch ever again. Have them both! Right now!",
      ingredients:"8 slices sourdough bread, 4 tablespoon unsalted butter, at room temperature, 8 ounces (2 cups) shredded cheddar cheese, 2 slicing tomatoes (such as beefsteak, Brandywine, or Cherokee purple), sliced 1/4-inch thick, 8 to 12 slices cooked bacon, 12 leaves butterhead or other crispy lettuce, Kosher salt and black pepper",
      servings:"2 servings",
      preptime:"10 mins",
      cooktime:"10 mins",
      totaltime:"20 mins",
      instructions:"Step 1:For each sandwich, spread 1 tablespoon butter on one side of two pieces of bread. Place the bread buttered-side down in a large skillet or on a griddle over medium-low heat. Sprinkle 2 ounces (1/2 cup) shredded cheese evenly over both slices. Cook until the cheese has melted and the bread is crisp, about 2 minutes. Melt the cheese: Step 2:Remove from the skillet. Layer one side with 2 to 3 pieces of bacon, the slices from half a tomato seasoned with some salt and pepper, and 3 leaves of lettuce. Close the sandwich. Repeat for remaining sandwiches. Slice in half and eat warm.",
      images:"https://www.simplyrecipes.com/thmb/RL8Rb8YxTCsd3ZmSijBI_InAP0Q=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2019__08__Grilled-Cheese-BLT-METHOD-3-1024x683-b860918a47f84480954ce5c8cad7e66a.jpg",
      allergens:"Milk",
      difficulty:"Medium",
    },
    {
      recipes_name:"Heart-Shaped Pepperoni Pizza",
      description:"Make a heart-shaped pepperoni pizza—complete with pepperoni hearts—for a festive Valentine’s Day or any pizza night with people you love.",
      ingredients:"(For the herb pizza sauce) 1 (15-ounce) can tomato sauce, 1 tablespoon extra virgin olive oil, 1 teaspoon kosher salt, 1 teaspoon dried basil, 1 teaspoon dried oregano, 1 teaspoon garlic powder, 1/2 teaspoon red pepper flakes, (For the pizza) 1 pound fully risen pizza dough, Flour, for dusting the counter, 10-12 large-diameter (about 1 1/2 inches) pepperoni slices, 12 ounces low-moisture mozzarella, shredded (about 3 cups), Fresh basil leaves, for garnish",
      servings:"2 to 3 servings",
      preptime:"10 mins",
      cooktime:"15 mins",
      totaltime:"25 mins",
      instructions:"Step 1:Preheat the oven to 500˚F: If you are using a pizza stone, preheat it in the oven so it gets nice and hot. Step 2: Make the herb pizza sauce: In a medium bowl, stir together all of the herb pizza sauce ingredients until they are combined. Set aside. Step 3:Shape the pepperoni: Fold each pepperoni in half, then use a paring knife or kitchen scissors to cut an angle off near the top of the fold. Then trim around the edge to form the point of the heart. Save all of your pepperoni trimmings—you will use them Step 4: Shape the pizza dough: Roll out the pizza dough into a large circle, at least 12 inches in diameter, on a lightly floured surface. You have two options for shaping into a heart: Option 1: Use a dough scraper, kitchen scissors, or pizza cutter to carve a heart out of the dough. This results in a cleaner looking heart, but you lose some dough. Option 2: Use your hands to shape the dough into a rough heart. You will keep more dough and have a thicker crust, but it is hard to get a really well-defined heart this way. Step 5: Top the pizza: Slide the shaped dough onto a pizza peel that’s dusted with flour. Spread 1/2 cup of the herb pizza sauce over the surface of the dough and top it with the reserved  pepperoni trimmings. Sprinkle on a layer of shredded cheese, and the heart-shaped pepperoni slices. Step 6: Bake and serve: Slide the pizza onto the pizza stone using a pizza peel and bake the pizza on the pizza stone for 10-12 minutes until golden brown around the edges and melted in the center (a pizza baked on a baking sheet will take longer, about 14-15 minutes). Garnish with fresh basil leaves. Let the pizza cool briefly, slice it, and serve.",
      images:"https://www.simplyrecipes.com/thmb/jN7t6uGRpzIM8OmqOcL_4IR-Ye0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Heart-Shaped-Pizza-LEAD-04-4a84c89f9d8d4fa692d04e58c22e5cd0.jpg",
      allergens:"eggs, milk, chili",
      difficulty:"Medium",
    },
    {
      recipes_name:"Masa for Tamales (Easy Tamale Dough)",
      description:"This basic tamale dough recipe will give you soft and fluffy tamales. Make the masa buy hand—it is a labor of love—or with an electric mixer in half the amount of time.",
      ingredients:"1 1/2 cups lard or vegetable shortening, at room temperature, 4 cups masa harina, 1 teaspoon baking powder, 1/2 tablespoon salt, 3 3/4 cups warm chicken stock or water, divided (see Recipe Note)",
      servings:"12 servings",
      preptime:"20 mins",
      cooktime:"0 mins",
      totaltime:"20 mins",
      instructions:"Step 1:Whip the lard: Place the lard or vegetable shortening in a large mixing bowl. Knead with your hands until it becomes light and airy, about 20 minutes—yes, it is a long time and that ss why it is a labor of love. Instead, you can beat it in a stand mixer fitted with a paddle attachment or hand mixer on medium speed for about 8 minutes. The lard will change from yellowish to white.  Step 2: Add the dry ingredients: Add the masa harina, baking powder, and salt to whipped lard, and continue mixing by hand, breaking up the large clumps of dough with your fingers. The mixture will be crumbly, resembling wet sand. You can do this with a stand mixer or handheld mixer—scrape the bottom and sides of the bowl with a rubber spatula a few times to incorporate any dry ingredients that may stick to the bowl.  Step 3: Add the liquid: Slowly stream in 3 1/2 cups chicken stock as you continue mixing the mixture with your hands for about 15 minutes or with an electric mixer for about 10 minutes on medium speed. Step 4: Test the masa: Drop a quarter-sized ball of masa in a glass filled with cold water. If the masa floats, it is ready. If it sinks, add the remaining 1/4 cup chicken stock, knead for 5 more minutes, and repeat the test. Continue kneading and testing until the ball floats to the top of the glass. The masa will be wet, spreadable, and sticky. Now you are ready to make tamales! The masa can be kept at room temperature for up to 4 hours and stored in a tightly sealed container in the refrigerator for up to 48 hours. The cold temperature will keep it from growing mold and the tightly sealed container will keep it from drying out. Any longer than 48 hours, it will sour. If you plan to make a large number of tamales, I recommend making the filling up to 2 days ahead, and the masa the day you plan to assemble your tamales. When assembling, keep the masa covered with a clean kitchen towel to avoid it from drying out.  ",
      images:"https://www.simplyrecipes.com/thmb/H1e_xGv3qa7rj7A34Qc45PgTEmE=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Masa-Dough-METHOD-08-7f8504854e2c453a9aa0d091df5ca833.jpg",
      allergens:"None",
      difficulty:"Easy",
    },
    {
      recipes_name:"Poblano, Corn, and Cheese Tamales",
      description:"Smoky, sweet, and cheesy, these are the best vegetarian tamales! Make sure to use a plant-based oil or vegetable shortening in the masa to make them truly vegetarian.",
      ingredients:"1 (8-ounce) package corn husks (see Recipe Note) 9 poblano peppers, 6 serrano peppers, 2 jalapeno peppers, 3 tablespoons olive oil, divided, 1/2 medium white onion, sliced (about 1 cup), 2 garlic cloves, roughly chopped, 1 (15-ounce) can corn, drained, or 10 ounces frozen corn, 6 cups masa for tamales (Recipe Note), 1 pound Monterey Jack cheese, sliced in 24 (2-inch long) strips, Sour cream, Homemade or store-bought salsa verde, Chopped cilantro",
      servings:"12 servings",
      preptime:"3 hrs 15 mins",
      cooktime:"112 mins",
      totaltime:"5 hrs 7 mins",
      instructions:"Step 1: Soak the corn husks:Rinse the corn husks thoroughly under warm running water to clean off any debris, being careful not to tear them. Place the rinsed husks in a large bowl with enough warm water to cover them. Use a heavy bowl or plate to weigh the husks down so that they stay submerged. I use the tejolote from my molcajete. Soak the husks for at least 2 hours so that they soften and become pliable. Step 2:Char the peppers:Preheat the broiler to high or 500°F. Rinse and pat the poblano, serrano, and jalapeño peppers dry with a kitchen towel. Lightly saturate a paper towel with 1 tablespoon of olive oil and rub the peppers with it. Place them on a large baking sheet. The serranos and jalapeños will give the tamales a spicy kick. If you prefer them to be milder, replace a few with another poblano pepper. Place the peppers under the broiler for 20 minutes, turning them every 5 minutes with tongs. Char them evenly all around. You can also roast the peppers directly on a gas stove burner. It will take more time and attention because the peppers will need to be constantly turned as direct contact with the flame roasts them unevenly and may cause the skins to turn to ash if not watched carefully. Plus, there will likely be a lot of smoke so open the windows! Transfer the charred peppers into a clean plastic bag or glass container with a lid. Seal tightly and let them steam for 10 minutes. Step 3:Clean the peppers: When the peppers are cool enough to handle, use the dull side of a paring knife or the back of a spoon to scrape the stem, skin, veins, and seeds off.Chop the peppers into 1/2-inch pieces. Set it aside. Step 4:Cook the filling: Heat the remaining 2 tablespoons olive oil in a large frying pan over medium heat. Add the onions and cook for 3 minutes, until they begin to soften. Add the garlic and cook for 1 minute, stirring frequently. Stir in the corn and chopped peppers, and cook for about 8 minutes. Remove the pan from the heat and set aside to cool to room temperature. Step 5:Assemble the tamales:Set up for assembling the tamales: You’ll need the soaked husks (keep them in the water), the masa, the poblano and corn filling, and the cheese. Lay a husk on a flat surface, smooth-side up and the pointyside away from you. Scoop about 1/3 cup masa and use a spoon to spread it onto the wider bottom half of the husk,leaving a 1/2-inch border around the bottom and side edges.",
      instructions:"Place about 3 tablespoons of the vegetable filling and a strip of cheese on the center of the masa. If you have a small husk, you may need to use less filling. Fold the husk in half lengthwise. Then, fold it half again lengthwise. Fold the pointy end up towards the wider end, and fasten with a strip of corn husk by tying it around the tamale so that it stays folded. Repeat until all the masa and filling are used. You will get about 24 tamales. Step 6: Prepare the steamer:Add water to a large steamer pot to the fill line, or until it comes up about 3 inches up the sides. Place the steamer basket on top. Line the steamer basket with a layer of husks. If your steamer is large like mine, place a heat-proof bowl upside down in the center. This will help keep tamales from tipping over. Place the tamales in the steamer basket upright, leaning against each other, the bowl (if using), and the pot. Cover the tamales with any remaining corn husks and then a clean kitchen towel. Cover the pot tightly with the lid. Step 7:Cook the tamales: Cook the tamales over medium-high heat. When the water comes to a boil, set the timer for 90 minutes. Check the water periodically to make sure it hasn’t fully evaporated, every 15 minutes—you may need to add more hot water. After 90 minutes, turn off the heat and let the tamales rest for 20 minutes in the steamer. To check for doneness, carefully remove a tamale from the pot with tongs and unwrap it. Please be very careful! The pot will be filled with steam and the kitchen towel covering the tamales will be very hot. The husk should easily detach from masa. Right out of the steamer, the tamale will be soft and wet. It will firm up and dry out after it rests a bit. Serve the tamales with a dollop of sour cream, salsa verde, and a sprinkle of chopped cilantro. Cooked tamales can last 3 to 4 days in the fridge and up to 6 months in the freezer. After cooking the tamales, let them cool completely. Then, pack them in zip top freezer bags for storing.    ",
      images:"https://www.simplyrecipes.com/thmb/dHfz1B1CRohcjf3oc1QrInnTMTc=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Poblano-Corn-Tamales-LEAD-06-844f518d09154fac8124816f4d0a2bf9.jpg",
      allergens:"Milk",
      difficulty:"Hard",
    },
    {
      recipes_name:"Brownie Banana Bread",
      description:"What could be better than homemade brownies or banana bread? Both desserts in one! Fold fudgy brownie chunks into tender banana bread for a treat that’ll have everyone asking for more.",
      instructions:"For the brownies: 10 tablespoons (140g) unsalted butter, 3/4 cup plus 2 tablespoons (85g) natural unsweetened cocoa powder, 1 1/4 cups (250g) sugar, 1/4 teaspoon salt, 2 eggs, straight from the refrigerator, 1 teaspoon vanilla extract, 1/2 cup (65g) all-purpose flour For the brownie banana bread: 1/3 cup (76g) unsalted butter, 3 medium very ripe bananas, peeled (1 1/4 to 1 1/2 cups mashed), 2/3 cup (137g) sugar, 1 large egg, 1 teaspoon vanilla extract, 1/4 teaspoon salt, 1 1/2 cups (205g) all-purpose flour, 1/2 teaspoon baking soda (not baking powder)",
      servings:"10 to 12 servings",
      preptime:"40 mins",
      cooktime:"85 mins",
      totaltime:"6 hrs 15 mins (Cool Time: 4hrs 10 mins)",
      instructions:"Step 1:Preheat the oven to 325°F. Line the bottom of an 8 x 8-inch square pan with parchment or foil, leaving a few inches of excess hanging on either side to create flaps. Grease the pan; if using foil, grease the foil, too. Step 2:Melt the butter:In a medium high-sided skillet or large saucepan, melt the butter over medium-low heat. Swirl the pan from time to time so the butter melts evenly. Step 3:Make the batter:Remove the pan from heat. Add the cocoa powder and whisk until smooth. Whisk in the sugar and salt; the mixture will be a lumpy, stiff mess, but that is fine. Whisk in the eggs, one at a time. Put some muscle into it. The mixture should now be very smooth. Whisk in the vanilla. Add the flour all at once. Switch to a spatula and vigorously beat in the flour, beating for 50 strokes to create a smooth batter. Scrape the batter into the prepared pan and smooth the top.  Step 4:Bake: Bake until a toothpick inserted in the center of the pan comes out with no wet streaks, about 25 minutes. Cool completely on a wire rack, then cover with foil and refrigerate for at least 4 hours. Step 5:Cut the brownie chunks:Use the parchment or foil handles to lift the cold, uncut brownie out of the pan and onto a cutting board. Cut in half; set the other half aside. Cut the chilled half-brownie into 1/2-inch chunks. This is what goes into the banana bread. You should have about 290 grams, or 2 to 2 1/2 cups of chunks. The remaining brownies you can just eat or save for later.",
      instructions:"Bake the banana bread Step 1: Preheat the oven to 350°F. Grease an 8 1/2 x 4 1/2 or 9 x 5-inch loaf pan. Step 2:Melt the butter: In a small saucepan or skillet, melt the butter over low heat. Set aside. Step 3:Make the banana bread batter: In a large bowl, mash the bananas as best you can using a whisk. Add the sugar and whisk vigorously; the sugar should help the bananas break down. Whisk in the egg, vanilla, and salt, then the melted butter. Switch to a spatula and fold in the flour and baking soda just until combined. If the batter is  thick like cement, add a few tablespoons of water to thin it out. Fold in the brownie chunks just enough to distribute them throughout the batter. Scrape the batter into the prepared pan. Step 4:Bake: Bake the loaf until the center of the top springs back when you gently press it with your fingertip, about 1 hour. Set the pan on a cooling rack and let the bread cool in the pan for 10 minutes. Turn the bread out of the pan and cool completely. Step 5:Store: Well wrapped, the bread will keep on the countertop for about 3 days. It also freezes beautifully.",
      images:"https://www.simplyrecipes.com/thmb/Wnn8u7MSUJTTHzMz4tP068JLHis=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes_Brownie-Banana-Bread-LEAD-06-adca125610bc4deea1405b256c150fc3.jpg",
      allergens:"Eggs, Flour, Nuts",
      difficulty:"Hard",
    },
    {
      recipes_name:"Chocolate Mayonnaise Sheet Cake",
      description:"Bake a fluffy and light chocolate sheet cake that is indulgent and incredibly tender, all thanks to a secret ingredient: mayonnaise! The decadent and velvety fudge buttercream frosting compliments the moist cake.",
      ingredients:"For the cake) Butter, for greasing the pan 2 cups (242g) all-purpose flour, 1 cup (120g) unsweetened Dutch processed cocoa powder, 1 1/2 teaspoons baking powder, 1 1/2 teaspoons baking soda, 1/4 teaspoon salt, 3/4 cup (177ml) hot water, 2 tablespoons (30g) instant coffee powder or instant espresso powder, 2 large eggs, 1 cup (220g) sugar, 1/2 cup (100g) brown sugar, lightly packed, 1 cup (260g) mayonnaise, 1 tablespoon vanilla extract (For the frosting) 1/2 cup (80g) finely chopped semisweet or bittersweet chocolate, 1/2 cup (113g) unsalted butter, 2 tablespoons (30g) unsweetened Dutch processed cocoa powder, 1 cup (130g) powdered sugar, 1/2 cup heavy cream",
      servings:"12 servings",
      preptime:"20 mins",
      cooktime:"30 mins",
      totaltime:"80 mins (Cool Time: 30mins)",
      instructions:"To make the cake Step 1:Preheat the oven: Preheat the oven to 350°F (180°C). Brush a 9x13-inch sheet pan with a little butter and set aside. Step 2:Mix the dry ingredients:In a medium bowl, stir together the all-purpose flour, cocoa powder, baking powder, baking soda and salt until evenly combined. Set aside. Step 3:Mix wet ingredients:In a glass measuring cup, add the instant coffee to the hot water. Mix until dissolved and set aside. Step 4:Beat the mayonnaise and sugars:In a large mixing bowl, beat the mayonnaise and white and brown sugars using an electric beater just until pale and creamy. Step 5:Add the eggs:Add the eggs one at a time and beat well. Make sure to scrape down the sides of the bowl with a spatula periodically to ensure everything is getting incorporated. Pour in the vanilla and beat to mix. Step 6:Fold the wet and dry ingredients together:Roughly divide the dry ingredients in thirds and add the first third to the egg mayonnaise mixture with half of the hot coffee. Beat until combined. Add the second part of the dry ingredients with the other half of the hot coffee and beat well. Add the final third of the dry ingredients and give it a good mix. The batter should be neither stiff nor runny. Step 7:Bake the cake: Pour the batter into the prepared tin and bake at 350°F (180°C) for 28-30 minutes or until a toothpick inserted into the center comes out with moist crumbs (not wet cake batter but sticky chocolate crumbs). Let the cake cool completely before frosting.",
      instructions:"To make the frosting Step 1:Melt the chocolate: In a small microwaveable bowl, melt the dark chocolate in a microwave using 20-second intervals until smooth, stirring between each interval. (It should take 40-70 seconds total). Set the chocolate aside to cool. Step 2:Beat the butter and sugar: In a large bowl, use an electric mixer to beat the butter until it’s creamy and fluffy. Add the powdered sugar to the creamed butter. Starting on the lowest speed, beat the mixture together. As the sugar gets incorporated, increase the speed and beat the frosting for 2-3 minutes on high speed. Step 3:Add the cocoa powder: Add the cocoa powder to the frosting and beat well until combined. Make sure to scrape down the sides every now and then for a smooth frosting. Step 4:Add the cream and cooled melted chocolate: Add the cream and melted dark chocolate to the frosting and beat well until combined. Let this set in the fridge for 10 minutes before frosting the cake. Step 5:Frost: Spread the frosting over the cooled cake and create a swirls using your spatula or the back of a spoon. Step 6:Serve and store: Slice and serve the cake. Once the cake is baked, leave it in the baking tin and cover it with plastic wrap. Leave it at room temperature for 1 day or refrigerate for up to 7 days. Once the sheet cake is frosted you can store it in the fridge for 3 days, however when you are ready to eat, let the cake come to room temperature before slicing as the frosting will be hard.",
      images:"https://www.simplyrecipes.com/thmb/EYivHw4fQ3emjLXvJtvW4YLsLk4=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Chocolate-Mayonnaise-Sheet-Cake-Lead-05-4a560dcc9d864a4caa8b5a2337b6d39a.jpg",
      allergens:"Eggs, Flour,",
      difficulty:"Hard",
    },
    {
      recipes_name:"Banoffee Pie",
      description:"Banoffee pie—with its sweet toffee, tropical banana, and giant peaks of whipped cream—is an unfussy, almost no-bake dessert that can brighten up even the gloomiest of days.",
      ingredients:"1 1/2 cups (190g) graham cracker crumbs, or about 12 whole graham crackers, 1/2 teaspoon ground cinnamon, 1/2 teaspoon kosher salt, 6 tablespoons (85g) unsalted butter, melted, 1 (13.4-ounce/380g) can dulce de leche, 2 to 3 medium bananas, yellow but not over-ripe, 1 1/2 cups (360ml) cold heavy cream, 2 tablespoons powdered sugar, 1 teaspoon vanilla extract, Chocolate shavings or cocoa powder, for topping",
      servings:"8 servings",
      preptime:"30 mins",
      cooktime:"10 mins",
      totaltime:"2 hrs 40 mins (Chill Time: 2 hrs)",
      instructions:"Step 1:Preheat the oven to 375°F. Step 2:Make the graham cracker crumbs (optional): If you are starting from whole graham crackers, use a food processor to grind them into fine crumbs. If you do not have a food processor, place the graham crackers in a 1-gallon zip-top bag and use a rolling pin to crush them into fine crumbs. Step 3: Make the crust: In a medium mixing bowl, stir the graham cracker crumbs, cinnamon, and salt together with a rubber spatula. Add the melted butter and mix until the crumbs are evenly moistened and the mixture looks sandy. Break up any large clumps with the spatula. Transfer the crumb mixture to a standard, 9-inch pie plate. Use your hand or the bottom of a measuring cup to press the crumbs firmly into an even layer along the bottom and up the sides of the pie plate to make a crust. Step 4:Bake the crust and add the dulce de leche: Bake the crust in the preheated oven for 10 minutes, or until it begins to turn golden. Let the crust cool completely, at least 30 minutes. Scrape the dulce de leche into the cooled pie crust and gently spread it into an even layer with an offset spatula or the back of a spoon. Step 5:Make the whipped cream: In the bowl of a stand mixer fitted with a whisk attachment, or in a large mixing bowl with a hand mixer, whip the heavy cream, powdered sugar, and vanilla on medium-high speed until stiff peaks form. The cream should thicken and when you pull the whisk out of the bowl, the peak should stand up. Do not overwhip the cream or it will curdle. Step 6:Assemble the pie: Peel the bananas and slice them into 1/4-inch thick rounds. Top the dulce de leche with the banana slices in an even layer. Spoon the whipped cream onto the pie and spread it to cover the bananas completely. Step 7: Chill: Refrigerate the pie, uncovered, for at least 2 hours and up to overnight. To serve, sprinkle the top of the pie with chocolate shavings or dust with cocoa powder. Store leftover pie, covered, in the refrigerator for up to 3 days. To prevent the exposed bananas from browning, press a small piece of parchment paper or plastic wrap against the cut edges.",
      images:"https://www.simplyrecipes.com/thmb/qfBtDNFOymA12HABI6D1KnM-ojc=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Banoffee-Pie-LEAD-07-6e5a92500fb94acf8a99533e2d9e13c7.jpg",
      allergens:"Milk",
      difficulty:"Hard",
    },
    {
      recipes_name:"Tamagoyaki",
      description:"Tamagoyaki is a soft and delicate rolled omelet and a classic Japanese dish. The technique to flip and roll the eggs may look tricky, but if I can do it, you can too!",
      ingredients:"",
      servings:"4 servings",
      preptime:"10 mins",
      cooktime:"10 mins",
      totaltime:"20 mins",
      instructions:"Step 1: Make the dashi stock: In a small bowl or glass measuring cup, combine the 1/4 cup warm water and dashi powder. Mix with a fork until the granules dissolve. The warm water simply helps them dissolve, so do not stress if you use room temperature or cold water. Step 2:Beat the eggs: In a medium bowl, add the eggs, sugar, and salt. Use a fork to beat the eggs until thoroughly combined. Try not to incorporate too many bubbles. Step 3:Season the eggs: Add the dashi stock, soy sauce, and mirin. Mix until the ingredients are incorporated. Step 4:Strain the eggs (optional): For a silkier custard-like texture, strain the eggs through a fine mesh strainer set over a liquid measuring cup with the spout—it will make pouring the egg batter into the pan easier. Step 5:Grease and heat the pan: Place the oil in a small bowl and dip a small, folded paper towel into it. Use the saturated paper towel to wipe the inside of a kotobuki tamagoyaki or small nonstick pan. Heat the skillet over medium heat, enough to immediately start cooking the eggs when they are added but not so hot that they brown right away, then reduce the heat to medium-low. Step 6:Cook the first layer: Pour a small amount of batter into the pan, just enough to fully coat the bottom. Cook until it is mostly set, with the top still slightly liquidy. Use chopsticks or a thin fish spatula to lift one end, flipping and rolling it over to the opposite end of the pan. Do not worry if the first couple of flips are wrinkled or scrunched up. Just keep on rolling with it. Step 8: Add two more layers: Use the oil-saturated paper towel to wipe the skillet with more oil, lifting the cooked egg up to get some oil under it. Then pour more egg batter in, just enough to coat the bottom of the pan. Lift the cooked egg up slightly and tilt the pan so the egg batter can get under it. Cook until it’s mostly set. Roll the eggs again the opposite direction, building up layers, sort of like building a snowman. Repeat this process one more time, oiling the pan, adding more egg batter, and rolling it back the other way. You will have used half the egg batter at this point. Slide the tamagoyaki onto a serving plate or a cutting board. Make a second tamagoyaki with the remaining batter following the same process.",
      instructions:"Step 9: Serve the tamagoyaki: Cut the tamagoyaki into 1-inch slices to reveal the swirls inside. Serve with grated daikon radish on the side, if you wouldd like, or as part of a larger Japanese-inspired meal. Leftovers can be refrigerated for 3 or 4 days. Though you can serve it cold, I like to remove it from the fridge and let it sit on the counter for 30 minutes or so to take the chill off. You can also heat it up briefly in the microwave in 15-second bursts until warmed through.",
      images:"https://www.simplyrecipes.com/thmb/uviP-Gj90Gdk7LBk6PC_tnOPYp4=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Tamagoyaki-LEAD-07-d8667860f87241bfb046d11374e9f594.jpg",
      allergens:"Eggs, soy",
      difficulty:"Hard",
    },
    {
      recipes_name:"French Omelette",
      description:"French omelettes have a reputation for being difficult to make, but with a little practice and just the right amount of confidence, we know you can nail it!",
      ingredients:"3 large eggs, Pinch of salt, Pinch of white pepper, 1 tablespoon unsalted butter, Finely chopped chives or parsley, for garnish",
      servings:"1 serving",
      preptime:"3 mins",
      cooktime:"5 mins",
      totaltime:"8 mins",
      instructions:"Step 1:Beat the eggs: In a medium bowl, whisk the eggs until no traces of white remain. Whisk in the salt and white pepper. Step 2:Melt the butter: In an 8-inch nonstick skillet with rounded sides set over medium heat, melt the butter, being careful not to let it brown. Swirl it around in the pan so it coats the bottom and sides. Step 3:Cook the eggs: Pour the eggs into the pan. With the bowl of a fork, tines facing up, rapidly stir the eggs. If you are concerned about scraping the nonstick surface of your pan, use a plastic fork. Move the fork all around the pan to break up the eggs as they cook. At the same time, hold the handle of the pan with the other hand and vigorously shake the pan back and forth. If the eggs cook too fast, forming large clumps, take the pan off the heat and keep stirring. The eggs will continue to cook a little from the residual heat. Cook until the eggs are loose and creamy with small curds. This will only take 2 to 3 minutes. Step 4:Roll the omelette: If you haven’t already done so, remove the pan from the heat. Run the fork around the edges to release the eggs. Tilt the pan to a 45-degree angle so that the eggs move to one side of the pan.  Keep the pan tilted and fold the eggs toward the edge until you have a half moon shape, running the fork under and around the eggs as needed to loosen them from the pan. With the pan still tilted, sharply tap the handle 2 or 3 times with your free hand to push the eggs over the edge by about 2 inches. If this makes no sense, that is okay—use a spatula to gently coax the eggs about 2 inches over the edge of the pan. Use your fork to fold the overhanging eggs up and towards the center of the omelette. It should now be almond-shaped Step 5:Transfer the omelette onto a plate: Hold onto the handle as close to the pan as possible. Bang the still tilted pan on the counter to move the omelette right up to the edge of the pan. Tilt a plate right next to the omelette and tip it onto the plate so the seam is on the bottom. Step 6:Serve the omelette Sprinkle with chives or parsley, if you’d like, and serve. The omelette is best eaten just after you make it. The texture will change, but you could wrap leftovers in plastic wrap and store it in the fridge for 3 to 4 days. To reheat, cover it with a dampened paper towel and microwave in 30-second intervals, until heated through. The key is to reheat it gently, so the eggs don’t overcook.",
      images:"https://www.simplyrecipes.com/thmb/4UuWv6U427Exu3DxEIE800CG9jI=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-French-Omlette-LEAD-05-3c570f5e0ef54576a41034d3ad598eeb.jpg",
      allergens:"Eggs",
      difficulty:"Medium",
    },
    {
      recipes_name:"French Toast",
      description:"The BEST French Toast! Fluffy and tender on the inside, gloriously browned on the outside. Learn how to make amazing French toast, including what bread to use, the perfect batter, and how to cook it.",
      ingredients:"4 large eggs, 2/3 cup milk, 2 teaspoons cinnamon, 8 thick slices 2-day-old bread (better if slightly stale), Butter (can sub vegetable oil), Maple syrup, 2 teaspoons freshly grated orange zest, Fresh berries",
      servings:"4 servings",
      preptime:"5 mins",
      cooktime:"15 mins",
      totaltime:"20 mins",
      instructions:"Step 1:Make the egg mixture: In a medium bowl, whisk together the eggs, milk, and cinnamon. Stir in the orange zest and/or triple sec if using. Whisk the mixture until well blended and pour into a shallow bowl, wide enough to place a slice of the bread you will be using. Step 2:Soak the bread slices in egg mixture: Place each slice of bread into the milk egg mixture, allowing the bread to soak in some of it. Step 3:Fry the French toast: Melt some butter in a large skillet over medium high heat. Shake off the excess egg mixture from the bread and place the bread slices onto the hot skillet. Fry the French toast until browned on one side, then flip and brown the other side. Step 4 Serve:Serve the French toast hot with butter, maple syrup, and/or fresh berries.",
      images:"https://www.simplyrecipes.com/thmb/pg5-C4UALcWhL7pSGNipE4TzGmA=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-French-Toast-Lead-Shot-2b-122aad46f39841e3bcb8830acc872993.jpg",
      allergens:"Eggs, Milk",
      difficulty:"Easy",
    },
    {
      recipes_name:"Huevos Rancheros",
      description:"Get set for the best Mexican breakfast recipe ever! Huevos rancheros are fried eggs served on a corn tortilla and smothered with warm salsa. Quick and easy to make!",
      ingredients:"1 tablespoon extra virgin olive oil, 1/2 medium onion, chopped, 1 (15-ounce) can whole or crushed tomatoes (preferably fire-roasted), or 1 to 2 large fresh tomatoes, when in season, 1/2 (6 ounce) can diced green Anaheim chiles, Chipotle chili powder, adobo sauce, or ground cumin to taste, optional, 4 corn tortillas, Butter, 4 large eggs, 2 tablespoons fresh cilantro, chopped, optional",
      servings:"2 to 4 servings",
      preptime:"0 mins",
      cooktime:"20 mins",
      totaltime:"20 mins",
      instructions:"Step 1:Make the salsa: Sauté the onions in a little olive oil in a large skillet on medium heat. Once the onions are translucent, add the tomatoes and their juices. If using whole canned tomatoes, break them up with your fingers or a spatula as you put them in the pan. If you are using fresh tomatoes, chop them first before adding. Note that fresh tomatoes will take longer to cook as canned tomatoes are already cooked to begin with. Add chopped green chilies. Add additional seasoning to taste, either chipotle chili powder, adobo sauce, regular chili powder, or even ground cumin.Bring to a simmer, reduce heat to low, and let simmer while you do the rest of the cooking, stirring occasionally. Reduce to warm after it has been simmering for 10 minutes. Add salt to taste, if needed. Step 2:Warm the plates: Heat the oven to 150°F. Place serving plates (not plastic, obviously) in the oven to keep warm. Step 3:Prepare the tortillas: Heat a teaspoon of olive oil in a large non-stick skillet on medium high, coating the pan with the oil. One by one (or more if your pan is big enough) heat the tortillas in the pan, a minute or two on each side until they are heated through, softened, and pockets of air bubble up inside of them.Remove and stack the tortillas on one of the warming plates in the oven to keep warm while you continue cooking the rest of the tortillas and the eggs Step 4:Fry the eggs:Using the same skillet you used for the tortillas, add a little butter to the pan, about two teaspoons for 4 eggs. Heat the pan on medium high heat. Crack 4 eggs into the skillet and cook for 3 to 4 minutes for runny yolks, a minute or two longer for firmer eggs. Step 5:Assemble and serve:To serve, spoon a little of the sauce onto a warmed plate. Top with a tortilla, then a fried egg. Top with more sauce, sprinkle with cilantro if desired. Serve either one or two eggs and tortillas per plate, depending on how much you want to eat. I'm a two-egg, two-tortilla person myself.",
      images:"https://www.simplyrecipes.com/thmb/LJtybgJVp1BjI2lR3rJruRpfyXQ=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2008__02__huevos-rancheros-horiz-a-1600-554b0519dd5a4b989995cef9761a6521.jpg",
      allergens:"Eggs,Chili,",
      difficulty:"Medium",
    },
    {
      recipes_name:"Homemade Pancake Mi",
      description:"Homemade Pancake Mix comes together in mere minutes and keeps for up to six months! Fluffy, buttery pancakes piled high on a Saturday morning are just a scoop away.",
      ingredients:"1 cup pancake mix, 3/4 cup milk, or 1 cup buttermilk, 1 large egg, 1 teaspoon vanilla extract, 1 tablespoon melted butter, plus more for the pan",
      servings:"2 to 3 servings",
      preptime:"5 mins",
      cooktime:"5 mins",
      totaltime:"10 mins",
      instructions:"Step 1:Make the mix: In a large bowl, combine flour, sugar, baking powder, baking soda, and salt. Whisk together. Transfer mix to an airtight container. Step 2:To make the pancakes: Put 1 cup of mix into a medium mixing bowl. In a separate small mixing bowl, combine milk, egg, and vanilla extract. Beat the egg with a fork or whisk until it is well incorporated with the milk and extract. Continue whisking the milk while you pour in the melted butter. Pour the egg mixture into the bowl with the pancake mix. Use a spatula to stir to combine. Do not worry about getting all the lumps out. Step 3:Cook the pancakes: Set a large skillet or griddle over medium heat. Once it is hot enough for a few droplets of water to dance on the top, add a tablespoon of butter. Once the butter melts, pour 1/3 cup of pancake batter onto the skillet to form a pancake. Repeat until the pan is filled, but not too crowded. Once bubbles form on the top and the edges of the pancake look slightly drier than the middle, flip the pancake. You should cook the pancake for about 3 minutes on the first side and 1 to 2 minutes after flipping. The pancakes should be lightly golden on both sides, with crispy edges Step 4:To serve: Serve with maple syrup or powdered sugar and fruit. If feeding a crowd, keep warm on a plate in a low oven until ready to serve",
      images:"https://www.simplyrecipes.com/thmb/6w2DPSfSs7FseQWuFb3NpWxW2O8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2019__05__Pancake-Mix-LEAD-07-3ccd43097f524b9790ffd26a6e213134.jpg",
      allergens:"Eggs, Flour",
      difficulty:"Easy",
    },
    {
      recipes_name:"Classic Chicken Salad",
      description:"This family favorite chicken salad is made with celery, bell pepper, green olives, apple, lettuce, and mayo—plus a secret ingredient that makes all the difference!",
      ingredients:"1 pound raw boneless, skinless chicken breasts, cut into 2 1/2-inch chunks (or 2 to 3 cups cooked chicken meat), 2 ribs celery, chopped, 1/2 red bell pepper, seeded and chopped, 4 to 6 green olives, pitted and minced, 1/4 cup chopped red onion, 1/2 to 1 apple, cored and chopped, 1/3 head iceberg lettuce, sliced and chopped, 5 tablespoons mayonnaise, 1 tablespoon plum preserves, or any sweet berry preserve (or a lesser amount of honey), 2 teaspoons freshly squeezed lemon juice, Salt and pepper to taste",
      servings:"4 servings",
      preptime:"10 mins",
      cooktime:"20 mins",
      totaltime:"30 mins",
      instructions:"Step 1:Poach the chicken (skip if using already cooked chicken):Bring a pot with 2 quarts of well salted water (1 tablespoon salt) to a boil. Add the chicken breast (cut into large chunks) and return the water to a simmer. Then turn off the heat, and cover the pot. Let the chicken sit for 15 minutes (time it) or more while you prepare everything else. Step 2:Make the dressing:Prepare the chicken salad dressing in a large bowl. Mix together the mayonnaise, preserves, and lemon juice. Taste for the proper balance of sweetness and acidity. The salad dressing should not be too sweet, nor too sour. Add more preserves or lemon juice until you have reached the balance you want. Add salt and pepper to taste. Step 3:Mix in the chopped celery, bell pepper, olives, red onion, and apple. Step 4:Dice the chicken, mix with dressing and vegetables:Remove the chicken from the poaching water and dice it. (Or dice already cooked chicken if that is what you are using for this salad.) Mix it in with the dressing and vegetables. Step 5:Add lettuce:At this point you can make ahead. When ready to serve, fold in the sliced and chopped iceberg lettuce.",
      images:"https://www.simplyrecipes.com/thmb/w9vQRolHr86DzWQF6zpDPit4bCo=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2018__07__Chicken-Salad-LEAD-1-e282629aeae54c198b8225819d3c4387.jpg",
      allergens:"Eggs",
      difficulty:"Easy",
    },
    {
      recipes_name:"Loaded Veggie Sandwich",
      description:"Make the most of summer produce—juicy tomatoes, crisp cucumbers, crunchy sprouts, and creamy avocado—with this loaded veggie sandwich. It’s easy to customize!",
      ingredients:"2 medium Persian cucumbers, 1 large heirloom tomato, 4 (1/2- to 3/4-inch) slices rustic sourdough or country bread, 2 to 3 teaspoons mayonnaise, 2 to 3 teaspoons stone-ground mustard, 1 medium ripe avocado, 1 cup broccoli or alfalfa sprouts, 2 pinches kosher salt, 2 pinches freshly ground black pepper, 1/4 cup pickled red onions, 2 large butter lettuce leaves, 2 to 4 slices (2 ounces) sharp cheddar cheese",
      servings:"2 servings",
      preptime:"10 mins",
      cooktime:"0 mins",
      totaltime:"10 mins",
      instructions:"Step 1:Prepare the vegetables:Trim the ends of the cucumbers and slice them lengthwise into 1/4-inch thick long strips. Core and slice the tomato into 1/3-inch slices. Step 2:Add the condiments and avocado:Spread 2 slices of bread with mayonnaise and 2 slices of bread with mustard. Arrange them so there is one of each for 2 sandwiches. Halve and pit the avocado. Slice one half into slices, peel, and add the avocado to a mustard-topped slice of bread. Use a knife to smear and lightly press the slices into the bread, mashing them a bit to help them adhere without damaging the bread. Step 3:Add the vegetables:Top the avocado with sprouts, dividing evenly between the 2 sandwiches. Add slices of tomato in a single layer on top of the sprouts. Sprinkle with salt and pepper.Divide the pickled red onions evenly between the 2 sandwiches on top of the tomato. Top each with a lettuce leaf, then slices of cheese. Finally, add the long slices of cucumber to each sandwich, then top with the mayo-slathered slices of bread, mayo-side down. Step 4:Serve:If desired, slice the sandwich in half down the center using a sharp chef’s knife. To help it stay together, poke a long toothpick in each half. Serve immediately. Any leftover sliced vegetables should be wrapped tightly and stored in the fridge for 1-2 days. Eat assembled sandwiches as soon as possible.",
      images:"https://www.simplyrecipes.com/thmb/cwInFpziMADFf_Ot4Nceu2DW0Xs=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Loaded-Veggie-Sandwich-METHOD-5-af5e0461470046eea43ca6a22a6cafa8.jpg",
      allergens:"Eggs",
      difficulty:"Easy",
    },
    {
      recipes_name:"Sesame Soba Noodles",
      description:"You will want these tasty sesame soba noodles in your lunchbox. The best part is that this soba noodle recipe takes less than 15 minutes to make.",
      ingredients:"9 ounces dry soba noodles (see Recipe Note), 1/4 cup toasted sesame oil, 3 tablespoons soy sauce, 2 tablespoons maple syrup or sugar, 2 tablespoons fresh lemon juice or rice vinegar, 2 tablespoons toasted sesame seeds (black or white), 2 green onions, roots trimmed and finely chopped, 1 clove garlic, grated with a Microplane, 1/4 teaspoon freshly ground black pepper",
      servings:"4 servings",
      preptime:"4 mins",
      cooktime:"10 mins",
      totaltime:"14 mins",
      instructions:"Step 1:Cook the soba noodles:Fill a large pot with about 3 quarts of water and set it over high heat. You don’t need to salt the water. Cover the pot with a lid if you’re hangry and need it to boil faster. When it comes up to a boil, add the soba noodles and cook for 4 minutes, stirring frequently with a large fork so that they don’t stick to each other or to the bottom of the pot.When it comes up to a boil, add the soba noodles and cook for 4 minutes, stirring frequently with a large fork so that they don’t stick to each other or to the bottom of the pot. Step 2:Meanwhile, make the dressing:In a large bowl, add the sesame oil, soy sauce, maple syrup, lemon juice, sesame seeds, green onions, garlic, and black pepper. Whisk well with a fork until combined. Step 3:Dress the noodles:Dress the noodles: Dress the noodles:    Step 4: Step 5: Step 6:",
      images:"https://www.simplyrecipes.com/thmb/VKiiyac-r40L1f5lkc_wMJkCr2Q=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Sesame-Soba-Noodles-LEAD-08-567d5502f67e442f832c82e2e066e072.jpg",
      allergens:"Eggs, Soy",
      difficulty:"Medium",
    },
    {
      recipes_name:"Homemade Pizza Bagel",
      description:"You can assemble and bake these deeply nostalgic pizza bagels in almost the same time it takes to pull the frozen kind out of the freezer. We call that a smart move!",
      ingredients:"4 full-sized plain bagels, halved, 1/2 cup store-bought or homemade pizza sauce, 8 ounces shredded mozzarella cheese, 4 ounces mini pepperoni, Dried basil, for garnish",
      servings:"4 servings",
      preptime:"5 mins",
      cooktime:"15 mins",
      totaltime:"20 mins",
      instructions:"Step 1:Preheat the oven to 400˚F. Step 2:Assemble the pizza bagels:For each half of a bagel, evenly spread 1 tablespoon pizza sauce. Top each with about 1 ounce of cheese and dot with a few mini pepperonis (or just divide the cheese an pepperoni between the bagels). Top all your bagel halves just like this. You should have 8. Lightly sprinkle each pizza bagel with a pinch of dried basil. Step 3:Bake the pizza bagels:Bake them for 8 to 10 minutes, until the cheese is melted and bubbly and the bagels are crispy around the edges. Serve them warm. Leftovers can be stored in the fridge for 3 to 4 days. Reheat in a 350°F oven until warmed through.",
      images:"https://www.simplyrecipes.com/thmb/gihK14l8W8k6RTflTZU5DizP2Tw=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Bagel-Pizza-METHOD-6-5bedbcd5953d4ff0b66f8043c84d9df9.jpg",
      allergens:"Flour, Eggs",
      difficulty:"Medium",
    },
    {
      recipes_name:"Bay Shrimp and Avocado Salad",
      description:"Easy shrimp and avocado salad! Pink shrimp and creamy avocado are a perfect match, especially with a crisp vinaigrette.",
      ingredients:"1/4 cup of white wine vinegar, 1/4 cup extra virgin olive oil, 1 green onion, thinly sliced, Pinch of salt, 3/4 pound cooked bay shrimp or extra small shrimp that are cooked, peeled, and de-veined, most of the shrimp roughly chopped, 3 ripe avocados, Lettuce - preferably butter lettuce or red leaf lettuce, Optional, 2 tablespoons chopped roasted hazelnuts, almonds, or pistachios,1 tablespoon chopped cilantro, Lemon slices for garnish",
      servings:"4 servings",
      preptime:"10 mins",
      cooktime:"0 mins",
      totaltime:"10 mins",
      instructions:"Step 1: Whisk together the oil, vinegar, chopped green onion and salt in a medium bowl. Add the shrimp and toss to coat with the dressing.Step 2:Arrange leaves of lettuce on individual plates. Cut two of the avocados in half and remove pits. (See How to Peel and Cut an Avocado.) With a spoon, carefully scoop out avocado halves from their skins in one piece. Place avocado half on plate with lettuce. Peel and chop the remaining avocado and mix it with the shrimp Step 3:Spoon shrimp mixture onto avocado. Sprinkle with nuts and/or cilantro if using. Serve with lemon slices for garnish.",
      images:"https://www.simplyrecipes.com/thmb/IQpR1BQ77X0enqpTkPC40l_58mU=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2004__08__shrimp-avocado-salad-vertical-b-1600-8c10d62579d34b76b2ddcecaf29575c5.jpg",
      allergens:"Shrimp",
      difficulty:"Easy",
    },
    {
      recipes_name:"Grilled Cheese Sandwich With Sauerkraut on Rye",
      description:"Grilled cheese sandwich with Gruyere Swiss cheese and sauerkraut on rye bread. Great combination!",
      ingredients:"2 slices dark rye bread, Several thin slices of aged, Gruyere Swiss cheese, 1/3 cup drained and heated sauerkraut, 2 teaspoons of butter",
      servings:"1 serving",
      preptime:"5 mins",
      cooktime:"10 mins",
      totaltime:"15 mins",
      instructions:"Step 1:Butter slices of bread on one side and place butter side down on hot frying pan:Heat a frying pan to medium high heat. For each slice of bread, butter one side and place slice butter side down on the hot pan. Step 2:Add cheese, sauerkraut, and top with cheese-less bread slice:Add a layer of cheese to one of the slices. As the bread begins to toast just slightly, and the cheese begins to soften, spread the heated sauerkraut over the slice of bread with cheese. Using a spatula, flip the cheese-less bread slice over on top of the slice with cheese and sauerkraut. Step 3:Flip the sandwich in the pan:After 30 sec or so, check to see if the cheese is just beginning to melt. If it is, flip the whole sandwich over onto the other side. Toast a minute more or less on that side until the cheese has melted, but isn't runny. Remove the sandwich from the pan. Slice in half.",
      images:"https://www.simplyrecipes.com/thmb/Enf-YdbLhQJ-8KxLEI1MKFmtuJE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2005__07__grilled-cheese-sandwich-sauerkraut-rye-horiz-a-1600-1a2030e354c141cabfeddc2a6f9cf260.jpg",
      allergens:"Eggs",
      difficulty:"Easy",
    },
    {
      recipes_name:"Air Fryer Salmon",
      description:"Perfectly cooked salmon in just 8 minutes? The air fryer can do that!",
      ingredients:"Nonstick spray, 4 (4- to 5-ounce) skin-on salmon fillets, 1 tablespoon olive oil, 1 teaspoon lemon pepper (or 1/2 teaspoon black pepper and 1 teaspoon fresh lemon zest), 1/2 teaspoon kosher salt, 1/4 teaspoon black pepper, Lemon wedges, for garnish",
      servings:"4 servings",
      preptime:"5 mins",
      cooktime:"10 mins",
      totaltime:"15 mins",
      instructions:"Step 1:Prepare the air fryer basket:Lightly spray the inside of the air fryer basket with nonstick cooking spray. Step 2:Season the salmon:Place the salmon on a plate skin side down. Drizzle the tops (the skinless sides) with olive oil and season with lemon pepper, salt, and black pepper. Step 3:Air fry the salmon:Place the salmon in the air fryer basket. Make sure they aren’t touching. I like to place mine skin-side down, but skin-side up is also an option. If you’d like, place a few lemon slices under each piece of salmon.Air fry the salmon for about 8 minutes at 350˚F. The salmon is done when it reaches an internal temperature of 135°F to 140˚F when measured with an instant read thermometer. You can cook it longer if you want a slightly more well-done piece. Step 4:Serve the salmon:Serve the salmon with fresh lemon wedges for squeezing on top.",
      images:"https://www.simplyrecipes.com/thmb/I6ozV07FfCO0nsTYoKbAa1fJkJ4=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Air-Fryer-Salmon-LEAD-02-0d0acca3a9cf4661a66154ae2b6fa78f.jpg",
      allergens:"Fish",
      difficulty:"Easy",
    },
    {
      recipes_name:"BLT Wraps",
      description:"Nothing says lunch like this BLT Wrap! Stuffed with crispy bacon, juicy tomatoes, and a tangy chive sauce, it's the perfect lunch for summer.",
      ingredients:"1 pound bacon, 1 head butter lettuce, leaves roughly chopped, 3 small ripe tomatoes, sliced, 6 large burrito-size tortilla wrap, 1/2 cup mayo, 2 tablespoons thinly sliced fresh chives, 1 tablespoon lemon juice, 1/2 teaspoon garlic powder, 1/8 teaspoon kosher salt",
      servings:"6 servings",
      preptime:"10 mins",
      cooktime:"20 mins",
      totaltime:"30 mins",
      instructions:"Step 1:Preheat oven to 375˚F. Step 2:Cook the bacon:Arrange the bacon on a few baking sheets with foil or elevate them on a wire rack, making sure the bacon is not overlapping.Bake the bacon for 15-20 minutes until it’s browned and crispy. Then remove the bacon from the baking sheet and let it drain on a few paper towels. Step 3:Make the chive mayo:In a medium bowl combine the mayo, chives, lemon juice, garlic powder, and salt. Set aside. Step 4:Assemble the wraps:Spread about 2 tablespoons of the chive mayo onto your wrap. Then layer with butter lettuce, tomato slices, followed by 3-4 strips of crispy bacon. Fold the edges over on the wrap and roll it into a tight cylinder. Cut the wrap in half for easier eating. Continue until all wraps are assembled. Step 5:Packing the wrap for lunch:Roll the wrap tightly in foil and keep it in the fridge until you leave. I like to pack the wraps in a bag with a cold pack, but they are fine wrapped up for a few hours also. I think the wrap is best when the lettuce is nice and crispy and cold.",
      images:"https://www.simplyrecipes.com/thmb/CzSFSzBEOsUXb8piRHCTCO-EFKc=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-BLT-Wraps-LEAD-02-75aa2ed533104c52bdb7407575cb7bc5.jpg",
      allergens:"Eggs",
      difficulty:"Easy",
    },
    {
      recipes_name:"Peach Dijon Pork Chops",
      description:"These pork chops are paired with peaches and Dijon mustard, a winning combination of sweet and tangy. Take a shortcut by using jarred peach preserves, and ask your butcher for rib chops, the best cut for quick cooking.",
      ingredients:"1/4 cup Diamond Crystal kosher salt (see recipe note), 3/4 cup dark brown sugar, tightly packed, 2 cups boiling water, 3 cups ice cubes, 4 center-cut, bone-in rib pork chops (about 1 inch thick), 1/2 cup chunky peach preserves, 1/2 cup Dijon mustard, 1 tablespoon finely chopped fresh rosemary, 1 tablespoon finely chopped fresh sage, 1/2 teaspoon freshly ground black pepper, Nonstick cooking spray",
      servings:"4 servings",
      preptime:"10 mins",
      cooktime:"12 mins",
      totaltime:"52 mins (Brining Time: 30 mins)",
      instructions:"Step 1:Make the brine:In a large heatproof bowl, combine the salt and brown sugar. Add the 2 cups of boiling water and stir to dissolve. Add the ice cubes and stir to cool. Step 2:Brine the pork chops:Submerge the pork chops in the brine, cover the bowl with plastic wrap, and brine for about 30 minutes. Do not brine any longer or the pork chops will be too salty. Step 3:Preheat the oven to 400°F. Step 4:Meanwhile, make the sauce:In a small bowl, stir together the peach preserve, Dijon, rosemary, and sage. Set it aside. Step 5:Clean and season the pork chops:Remove the pork chops from the brine, rinse well under cold running water, and thoroughly pat them dry with paper towels. Discard the brine. Season the pork chops with the black pepper. Step 6:Cook the pork chops:Lightly spray a large oven-proof grill pan or skillet with nonstick cooking spray. Set it over high heat. Add the pork chops without crowding the pan. You may need to cook them in batches if the pan isn’t big enough. Sear for about 2 minutes, until bottoms are golden brown, then flip them. Immediately spread the sauce on top of each pork chop.Transfer the pan into the oven. Roast the chops until cooked through and an instant read thermometer inserted into the center registers 140°F to 145°F, 8 to 10 minutes.Let rest for 1 to 2 minutes to let the juices redistribute and serve. Bon appétit, y’all!",
      images:"https://www.simplyrecipes.com/thmb/3gfLKOJ8nzynUJYDB4cYPcnEO5o=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Peach-Dijon-Pork-Chops-LEAD-5-6b249f5452ca45449463a3a4373b0e8b.jpg",
      allergens:"None",
      difficulty:"Hard",
    },
    {
      recipes_name:"How to Make a Burger on the Stove",
      description:"No grill, no problemo! Here's how to make an incredible burger indoors on the stove. An optional quick seasoning mix takes it to the next level.",
      ingredients:"1 tablespoon kosher salt, 1 tablespoon black pepper, 1 teaspoon garlic powder, 1/4 cup mayonnaise, 1 tablespoon Dijon mustard, 1 tablespoon ketchup, 1 pound ground chuck (90:10), 3 potato or brioche buns, 6 slices American cheese, Nonstick spray, Green lettuce leaves, Thinly sliced red onion, Thinly sliced fresh tomato",
      servings:"3 servings",
      preptime:"5 mins",
      cooktime:"10 mins",
      totaltime:"15 mins",
      instructions:"Step 1:Prepare the optional burger seasoning mix:Before you start cooking, prepare the seasoning mix. In a small bowl, mix together the salt, pepper, and garlic powder. Set aside. Step 2:Make the sauce:In another small bowl, mix the mayonnaise, mustard, and ketchup together until smooth. Set aside. Step 3:Form the burgers:Preheat a large sturdy skillet (cast iron is best) over medium heat. Loosely divide the ground beef into three 1/3-pound patties. Shape into discs about 1/2 inch thick and put a divot in the center of each patty to prevent swelling in the center. Season the patties with 1/2 teaspoon of seasoning mix per side of the patty, if using. Step 4:Cook the burgers:Turn on the fan over the stove and open a window to help with air flow. Spray your skillet with a little non-stick spray and place burgers in the skillet. Press down on each patty with a spatula for 10 seconds. This is to encourage browning. Cook the burgers over medium heat for 4 minutes. Don’t touch them too much so you get a nice crust on the first side. Use a sturdy metal spatula to flip the burgers, being sure to scrape up any caramelization with the burger. Step 5:Flip the burgers:After you flip the burgers, add the cheese, if using, and continue to cook for 3 minutes until the burger is cooked to desired doneness, usually medium. If you are only cooking one burger, you can toast your buns in the same skillet as your patty, or you can toast them separately if you are cooking multiple burgers at once. If you want the cheese to be very melted, cover the burgers with a lid for the last minute of cooking. Step 6:Build the burgers and serve: Build your burgers by spreading some burger sauce on each bun. Put the burgers on the bottom bun and top with the lettuce, onions, tomatoes, and the top bun. Serve immediately with a cold drink.",
      images:"https://www.simplyrecipes.com/thmb/LoTvUq4ueNjolH2tALJ8S1WcpN4=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Burger-On-Stovetop-LEAD-03-024b974809034fe7a7daf9e9eda5606a.jpg",
      allergens:"Eggs",
      difficulty:"Medium",
    },
    {
      recipes_name:"Stir-Fried Maitake Mushrooms with Garlic and Chile Oil",
      description:"The simplest way to enjoy the full flavor of fall’s mushrooms is to stir-fry them quickly with just a touch of garlic and a hint of heat",
      ingredients:"1 tablespoon Chinese light soy sauce, 2 tablespoons cool water (if needed), 3 tablespoons vegetable oil, 1/4 cup thinly sliced garlic (from about 6 cloves), 12 ounces (about 5 very loosely packed cups) maitake mushrooms, pulled into small 2-inch chunks, 1-2 teaspoons chile oil (see method in article above) or chile crisp",
      servings:"4 servings",
      preptime:"5 mins",
      cooktime:"8 mins",
      totaltime:"13 mins",
      instructions:"Step 1:Prep the ingredients: Place the soy sauce in a small bowl. Place the water in a separate small bowl and set both aside. Step 2:Cook the garlic: Heat the oil in a wok (or a large skillet) over high heat until it shimmers. Add the garlic, and cook, stirring frequently with a wok shovel or a wooden spoon, until it is golden and just beginning to turn light brown, about 1 minute. Use a slotted spoon (or just your stirring spoon) to remove the garlic from the pan, leaving the oil. Set the garlic aside. Step 3:Cook the mushrooms: Add the mushrooms to the oil and stir-fry them—flipping and stirring occasionally and pressing them against the sides of the wok for 20 to 30 seconds at a time, so they brown a bit—for 3 minutes total. If the mushrooms are browning quickly but are not beginning to wilt, drizzle in the water, to help them soften. Step 4:Add soy sauce to the mushrooms: Drizzle the soy sauce over the mushrooms, then continue to cook them for another 2 minutes, until the liquid is fully absorbed, and the mushrooms look soft and tender. Step 5: Add the chile oil: Drizzle in the chile oil and mix everything well. Step 6:Serve: Transfer the mushrooms to a serving bowl, and enjoy while hot with rice and other Chinese dishes.",
      images:"https://www.simplyrecipes.com/thmb/Iyv6Sn9CuSSGBVUKPT9p6tbe5QQ=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Mushroom-Garlic-Chile-METHOD-06-467b0a6e8ced4783bf5e5ddf3c68fb33.jpg",
      allergens:"Soy",
      difficulty:"Medium",
    },
    {
      recipes_name:"Shrimp and Mushroom Stir Fry",
      description:"You’ll want to keep this quick shrimp and mushroom stir fry recipe in your back pocket for easy, wholesome dinners. It comes together in just a few minutes and is a great weeknight meal.",
      ingredients:"12 ounces cremini mushrooms, quartered or sliced, 1 pound large shrimp (31-35 per pound), peeled, 2 tablespoons olive oil, 3 scallions, chopped, 1 1/2 cups chicken stock, 3 cloves garlic, minced, 1/4 cup soy sauce, 2 tablespoons cornstarch, Cooked white rice, to serve, Sesame seeds, for garnish",
      servings:"4 servings",
      preptime:"10 mins",
      cooktime:"15 mins",
      totaltime:"25 mins",
      instructions:"Step 1:Make the stir fry sauce:Whisk together the chicken stock, garlic, soy sauce, and cornstarch in a small bowl. Set aside. Step 2:Cook the mushrooms:In a large skillet or wok over medium heat, add olive oil and mushrooms. Cook until the mushrooms soften and turn brown in spots around the edges, about 8 minutes. Step 3:Add the shrimp:Once the mushrooms are cooked to your liking, add the shrimp to the skillet. If the skillet is very dry, add a fresh drizzle of oil to it to ensure the shrimp doesn’t stick. Cook, stirring constantly, until shrimp are cooked through and no longer translucent, 2-3 minutes. Step 4:Finish the stir fry:Once shrimp are cooked, add all the stir fry sauce to the skillet and stir to combine. The finished sauce should just coat the stir fry ingredients, almost like a thin gravy. If the sauce thickens too much, stir in extra water by the tablespoon. If the sauce is too thin, let it simmer for 1-2 minutes and it will thicken. Lastly, stir in the chopped scallions. Step 5:Serve: Serve the shrimp stir fry spooned over cooked white rice garnished with sesame seeds.",
      images:"https://www.simplyrecipes.com/thmb/fcURjFW0GCdDELVFNpMHVwXm42Y=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Shrimp-Mushroom-Stir-Fry-LEAD-01-f46969f2ceaf48db81f8a0a208ed109d.jpg",
      allergens:"Shrimp, Soy, Sesame seeds",
      difficulty:"Medium",
    },


]
const seedsrecipes = ()=> Recipes.bulkCreate(recipes)
module.exports = seedsrecipes


//https://www.simplyrecipes.com/